<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b4645549-80af-496f-b7a7-aa3dc6c53ab3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.4.6" />
    <PackageReference Include="Aspire.Microsoft.Azure.StackExchangeRedis" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.4.6" />
    <PackageReference Include="Google.Apis.Cloudchannel.v1" Version="1.75.0.4176" />
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="3.36.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GChannel.ServiceDefaults\GChannel.ServiceDefaults.csproj" />
    <ProjectReference Include="..\GChannel.Shared\GChannel.Shared.csproj" />
  </ItemGroup>

</Project>
