<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c8d2f7a1-4f3b-4f9d-9c2a-7e6b1a0d5e44</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GChannel.ServiceDefaults\GChannel.ServiceDefaults.csproj" />
    <ProjectReference Include="..\GChannel.ApiService\GChannel.ApiService.csproj" />
  </ItemGroup>

</Project>
